// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lvxhaolstwcsmrnkdruj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx2eGhhb2xzdHdjc21ybmtkcnVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg5MjMwNzgsImV4cCI6MjA1NDQ5OTA3OH0.XmyIutpC2pIzVij1F-I6a9GY6ZJ0lxBXVOUVOCr_poM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);